### ISSUE TITLE
UEFI Not supported with Ventoy

### ISSUE THREAD

**Issue by Apxdono** [arch-linux-gui/arch-linux-gui-pure#2]
Good day.
Downloaded pure plasma version of the installer today (iso info below) and added it to Ventoy flash drive that I have (works with other UEFI ISOs like KDE Neon, Manjaro, and Windows). Upon selecting the ALG image I get an error message that image doesn't have UEFI x64 support.

Is this expected behavior and ALG ISOs should be flashed directly on a flashdrive?
```
# info
Filename: archlinux-gui-plasma-pure-2021.12-x86_64.iso
SHA1: d0cad64a4ebd2638165e6407d0fc6e07f1d380ca
MD5: a5eb829c5f86b5171e12b73864fa02da
```

**Comment by ghost** [comment]
can u send detailed information on this

**Comment by Apxdono** [comment]
Good time of day, sorry for the long delay @KrishivS.
Can you please specify exactly what info you're after?
